### ISSUE TITLE
添加代码折叠

### ISSUE THREAD

**Issue by mars00772** [bubkoo/hexo-filter-fenced-code#1]
fenced-code强大无比，与自带的相比，功能强大了许多，要是能添加代码折叠方案，想必是极好的

**Comment by bubkoo** [comment]
代码折叠已经不是该 filter 做的事情，而是需要在博客主题中选择支持代码折叠的 highlight 模块

**Comment by mars00772** [comment]
oh，求推荐

**Comment by bubkoo** [comment]
没有直接可以用的，需要自己研究一下 Hexo 的 render
